experiment:
  name: trajectory_generation
  output_dir: experiments
  seed: 42

data:
  num_trajectories: 10000
  trajectory_length: 50
  input_dim: 7
  output_dim: 7
  workspace_bounds:
    - [-1, 1]
    - [-1, 1]
    - [0, 2]
  add_noise: true
  noise_std: 0.01

models:
  diffusion_policy:
    enabled: true
    architecture:
      horizon: 16
      num_steps: 100
      unet_dim: 256
      num_layers: 4
      time_embed_dim: 128
      beta_schedule: cosine
      prediction_type: epsilon
      dropout: 0.1

  transformer:
    enabled: true
    d_model: 256
    nhead: 8
    num_layers: 6
    dim_feedforward: 1024
    dropout: 0.1
    max_seq_length: 50

  vae:
    enabled: true
    latent_dim: 64
    hidden_dim: 256
    num_layers: 3
    dropout: 0.1
    beta: 1.0

  mlp:
    enabled: true
    hidden_dim: 256
    num_layers: 4
    dropout: 0.1
    activation: relu
    use_batch_norm: false
    use_residual: false

  gflownets:
    enabled: true
    hidden_dim: 256
    num_layers: 4
    dropout: 0.1
    max_trajectory_length: 50
    temperature: 1.0

training:
  batch_size: 32
  learning_rate: 0.0001
  num_epochs: 100
  optimizer: adam
  scheduler: cosine
  gradient_clip: 1.0
  early_stopping:
    patience: 10
    min_delta: 0.000001
  validation_freq: 5
  checkpoint_freq: 10

evaluation:
  metrics:
    - mse
    - smoothness
    - end_error
  num_samples: 100
  visualization: true